orbs: 
  ta-docker: travelaudience/docker@3.2

version: 2.1
workflows:
  docker-push:
    jobs:
    - ta-docker/build_and_push:
          name: docker-cloudsql-goose
          context: docker-registry-access
          image-name: "docker-cloudsql-goose"


